version: "3"

services:
  mongodb:
    image: mongo:latest
    command: mongod --dbpath /data/db
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: p@ssw0rd
    ports:
      - "27017:27017"
