version: "3"

services:
  mongodb:
    image: mongo:latest
    command: mongod --dbpath /data/db
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: p@ssw0rd
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  postgres:
    image: postgres:latest
    restart: always
    container_name: "postgres"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "25432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
networks:
  rabbitmq_go_net:
    driver: bridge
  fullstack:
    driver: bridge
